# Generated by Django 5.0.6 on 2025-11-16 16:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0004_remove_category_thumbnail_remove_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
